#!/bin/bash

HAS_ISSUES=0
FIRST_FILE=1

for file in $(git diff --name-only --staged -- '*.rs'); do
  FMT_RESULT="$(rustfmt --edition 2021 --check $file)"
  if [ "$FMT_RESULT" != "" ]; then
    echo "$file KO"
    HAS_ISSUES=1
  fi
done

if [ $HAS_ISSUES -eq 0 ]; then
exit 0
fi

echo "Your code has formatting issues. Format with cargo fmt."
exit 1
