// rollup.config.js
import typescript from 'rollup-plugin-typescript2';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import serve from 'rollup-plugin-serve';
import sourcemaps from 'rollup-plugin-sourcemaps'
import copy from 'rollup-plugin-copy';

const isWatch = process.env.ROLLUP_WATCH;

export default [{
  input: 'dev/load-one-file.ts',
  output: {
    name: 'Dev',
    file: 'dev/dist/load-one-file.js',
    format: 'umd',
    sourcemap: true,
  },
  plugins: [
    resolve(),
    commonjs(),
    typescript(),
    sourcemaps({
      // Sourcemap for typescript files are generated by typescript and should
      // not be messed around by the sourcemap plugin, only used for external
      // libraries
      exclude: ['**/*.ts'],
    }),
    copy({
      targets: [
        { src: 'dev/index.html', dest: 'dev/dist/' },
        { src: 'dev/load-one-file.html', dest: 'dev/dist/' },
      ],
      verbose: true,
      copyOnce: true,
    }),
    isWatch && serve('dev/dist'),
  ],
}, {
  input: 'dev/split.ts',
  output: {
    name: 'Dev',
    file: 'dev/dist/split.js',
    format: 'umd',
    sourcemap: true,
  },
  plugins: [
    resolve(),
    commonjs(),
    typescript(),
    sourcemaps({
      // Sourcemap for typescript files are generated by typescript and should
      // not be messed around by the sourcemap plugin, only used for external
      // libraries
      exclude: ['**/*.ts'],
    }),
    copy({
      targets: [
        { src: 'dev/split.html', dest: 'dev/dist/' },
      ],
      verbose: true,
      copyOnce: true,
    }),
    isWatch && serve('dev/dist'),
  ],
}]
