indexing:
  fields:
    studies:
      - StudyInstanceUID
      - PatientName
      - PatientID
      - PatientBirthDate
      - AccessionNumber
      - ReferringPhysicianName
      - StudyDate
      - StudyDescription
    series:
      - SeriesInstanceUID
      - BitsAllocated
      - Columns
      - NumberOfFrames
      - Modality
      - Rows
      - PhotometricInterpretation
      - PixelRepresentation
      - PerformedProcedureStepStartDate
    instances:
      - SOPInstanceUID
table_name: dicom_index
