indexing:
  fields:
    studies:
      - StudyInstanceUID
      - PatientName
    series:
      - SeriesInstanceUID
      - BitsAllocated
      - Columns
      - NumberOfFrames
      - Modality
      - Rows
      - PhotometricInterpretation
      - PixelRepresentation
    instances: []
table_name: dicom_index
