# To build a fully static executable
# see https://stackoverflow.com/a/67616507/2603925
# note that you need to add the --target option for this to work like: `--target x86_64-unknown-linux-gnu`.
# See https://github.com/rust-lang/rust/issues/78210#issuecomment-714600426
[build]
rustflags = [
  "-C", "target-feature=+crt-static",
]

[target.wasm32-unknown-unknown]
rustflags = [
  # https://stackoverflow.com/questions/76452839/how-to-compile-rust-for-use-with-wasms-shared-memory
  "-C", "link-args=--import-memory",
  "-C", "link-args=-z stack-size=10000000",
]

# target = "x86_64-unknown-linux-gnu"
## we can't force musl target here if we want the conditional target for wasm
# target = "x86_64-unknown-linux-musl"
