# To build a fully static executable
# see https://stackoverflow.com/a/67616507/2603925
[build]
rustflags = [
  "-C", "target-feature=+crt-static",
  # https://stackoverflow.com/questions/76452839/how-to-compile-rust-for-use-with-wasms-shared-memory
  "-C", "link-args=--import-memory",
]
# target = "x86_64-unknown-linux-gnu"
target = "x86_64-unknown-linux-musl"
