name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install musl-tools
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - name: Update rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --verbose --all-features --target x86_64-unknown-linux-musl
      - name: Test
        run: cargo test --verbose --all-features --target x86_64-unknown-linux-musl
