# https://github.com/marketplace/actions/upload-files-to-a-github-release

name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    env:
      archive_name: rdicom-tools-linux-amd64-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3
    - name: Build tools
      run: cargo build --release --locked --all-features
    - name: Compress tools
      run: |
        mkdir -p ${{ env.archive_name }}
        cp target/x86_64-unknown-linux-gnu/release/{dump,scan,serve,dcm2xml,dcm2json} ${{ env.archive_name }}
        tar zcvf ${{ env.archive_name }}.tar.gz ${{ env.archive_name }}
    - name: Upload tools
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.archive_name }}.tar.gz
        asset_name: ${{ env.archive_name }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: "rdicom tools"
