import sourcemaps from 'rollup-plugin-sourcemaps';
import typescript from 'rollup-plugin-typescript2';
import terser from '@rollup/plugin-terser';
import copy from 'rollup-plugin-copy';
import arraybuffer from '@wemap/rollup-plugin-arraybuffer';

const isWatch = process.env.ROLLUP_WATCH;

const config = {
  input: 'src/index.ts',
  output: [{
    name: 'rdicom',
    file: 'dist/index.js',
    format: 'umd',
    sourcemap: true,
  }],
  plugins: [
    arraybuffer({ include: '**/*.wasm' }),
    sourcemaps({
      // Sourcemap for typescript files are generated by typescript and should
      // not be messed around by the sourcemap plugin, only used for external
      // libraries
      exclude: ['**/*.ts'],
    }),
    typescript(),
    copy({
      targets: [
        { src: '../target/wasm32-unknown-unknown/release/rdicom.wasm', dest: 'dist/' },
      ],
      verbose: true,
      copyOnce: true,
    }),
  ],
}

if (!isWatch) {
  config.output.push({
    name: 'rdicom',
    file: 'dist/index.min.js',
    format: 'umd',
    plugins: [terser()],
  });
}

export default config;
